import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Gaurav",
      email: "gaurav25narula@gmail.com",
      password: bcrypt.hashSync("1234", 8),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456", 8),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Lemon Pickle",
      category: "Pickle",
      image: "/images/p1.jpg",
      price: 120,
      countInStock: 10,
      brand: "HappyyEatingg",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Mango Pickle",
      category: "Pickle",
      image: "/images/p2.jpg",
      price: 100,
      countInStock: 20,
      brand: "HappyyEatingg",
      rating: 4.0,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Raw Mango Chutney",
      category: "Chutney",
      image: "/images/p3.jpg",
      price: 220,
      countInStock: 0,
      brand: "HappyyEatingg",
      rating: 4.5,
      numReviews: 17,
      description: "High quality product",
    },
    {
      name: "Green Chilly Pickle",
      category: "Pickle",
      image: "/images/p4.jpg",
      price: 78,
      countInStock: 15,
      brand: "HappyyEatingg",
      rating: 4.5,
      numReviews: 14,
      description: "High quality product",
    },
    {
      name: "Besan ke Ladoo",
      category: "Ladoo",
      image: "/images/p5.jpg",
      price: 65,
      countInStock: 5,
      brand: "HappyyEatingg",
      rating: 4.5,
      numReviews: 10,
      description: "High quality product",
    },
    {
      name: "Flax Seeds Dry Fruit Ladoo",
      category: "Ladoo",
      image: "/images/p6.jpg",
      price: 120,
      countInStock: 12,
      brand: "HappyyEatingg",
      rating: 4.5,
      numReviews: 15,
      description: "High quality product",
    },
    {
      name: "Aate ke Ladoo",
      category: "Ladoo",
      image: "/images/p7.jpg",
      price: 350,
      countInStock: 15,
      brand: "HappyyEatingg",
      rating: 4.0,
      numReviews: 15,
      description: "High quality product",
    },
  ],
};
export default data;
